name: weather_forecast
description: "Mobile Challenge ProjectMark"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Archivo/
    - assets/images/icons/
    - assets/images/logos/
    - assets/images/backgrounds/

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo/Archivo-Thin.ttf
          weight: 100
        - asset: assets/fonts/Archivo/Archivo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo/Archivo-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo/Archivo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo/Archivo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo/Archivo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Archivo/Archivo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo/Archivo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Archivo/Archivo-Black.ttf
          weight: 900